# 使用官方 MySQL 镜像作为基础镜像
FROM mysql:8.0

# 设置环境变量，用于配置 MySQL 的 root 用户密码
ENV MYSQL_ROOT_PASSWORD=root
# 创建一个新的数据库
ENV MYSQL_DATABASE=local_test
# 创建一个新的用户
ENV MYSQL_USER=test
# 设置新用户的密码
ENV MYSQL_PASSWORD=123456

# 暴露 MySQL 默认端口
EXPOSE 3306

# 容器启动时执行的命令，这里使用官方镜像默认的启动命令
CMD ["mysqld"]
